repeat_video: true
file_path: /opt/dsl/videos/shared/wangsan-test1.mp4
class_agnostic_1: true
class_agnostic_2: true
preprocessing_1: false
preprocessing_2: false
postprocessing_1: true
postprocessing_2: true
postprocess_1: NMM
postprocess_2: NMM
match_metric_1: IOS
match_metric_2: IOS
match_threshold_1: 0.8
match_threshold_2: 0.8
num_labels: 7
interval_1: 2
interval_2: 2
trk_method_1: IOU
trk_method_2: IOU
trk_width_1: 640
trk_width_2: 640
trK_height_1: 480
trK_height_2: 480
sink_width: 960
sink_height: 640
batch_size: 4
primary_infer_config_file_1: /opt/dsl/datas/002-cu114/config_infer_primary_yoloV5s.txt
primary_infer_config_file_2: /opt/dsl/datas/002-cu114/config_infer_primary_yoloV5s_2.txt
preprocess_config_file_1: /opt/dsl/datas/002-cu114/config_preprocess_v5s.txt
preprocess_config_file_2: /opt/dsl/datas/002-cu114/config_preprocess_v5s_2.txt
primary_model_engine_file_1: /opt/dsl/datas/002-cu114/model_b4_gpu0_fp16.engine
primary_model_engine_file_2: /opt/dsl/datas/002-cu114/model_b4_gpu0_fp16.engine
tracker_config_file_1: /opt/dsl/datas/002-cu114/config_tracker_IOU.yml
tracker_config_file_2: /opt/dsl/datas/002-cu114/config_tracker_IOU.yml

