# VIDEO_ROOT_DIR
# DATA_ROOT_DIR
# usage export VIDEO_ROOT_DIR=? 

inputs: video
repeat_video: false
rtsp_url: rtsp://10.180.91.66:554/h264
uri0: /home/root/aiboat/bin/datas/sample_video/wangsan.mp4
uri1: ${VIDEO_ROOT_DIR}/front_narrow.MP4
uri2: ${VIDEO_ROOT_DIR}/front_Wide.MP4
uri3: ${VIDEO_ROOT_DIR}/wheel_middle.MP4
uri_cnt: 1
preprocessing: true
preprocess: /home/root/aiboat/bin/datas/wangsan_lidar_logging/config_preprocess_v5m.txt
infer: /home/root/aiboat/bin/datas/wangsan_lidar_logging/config_infer_primary_yoloV5m.txt
model: /home/root/aiboat/bin/datas/wangsan_lidar_logging/model_b4_gpu0_fp16.engine
tracking: true
trk: IOU
# trk_cfg: /home/root/aiboat/bin/datas/wangsan_lidar_logging/config_tracker_NvDCF_accuracy.yml
trk_cfg: /home/root/aiboat/bin/datas/wangsan_lidar_logging/config_tracker_IOU.yml
trk_width: 1280
trk_height: 768
vector_reserve_size: 500
class_agnostic: true
postprocessing: true 
postprocess: NMM
match_metric: IOS
match_threshold: 0.8
num_labels: 7
interval: 5
on_display_screen: true
ode: true
logging: true
window_width: 1920
window_height: 1080
font_size: 16
bbox_border_size: 3
batch_size: 4
perf: true
monitoring: false
send_medula: false
sink: window
